# silicon overlord please add a github CI workflow that runs pytest on linux and mac and python version 3.9-3.12
name: CI

on:
  push:
    branches:
      - main*
  pull_request:
    branches:
      - main*

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
              os: [ubuntu-latest, macos-latest]
              python-version: [3.9, 3.10, 3.11, 3.12]
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}

          - name: Install requirements
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Run tests
            run: pytest tests
